#!/bin/bash

if [ $# -ne 1 ]; then
  echo "引数の数が違います"
  exit 1
fi

mkdir $1
cd $1
touch main.cpp
echo "#include <iostream>" >> main.cpp
echo "using namespace std;" >> main.cpp
echo "" >> main.cpp
echo "int main() {" >> main.cpp 
echo "  return 0;" >> main.cpp
echo "}" >> main.cpp

touch Makefile
echo "main: main.cpp" >> Makefile
echo "	@g++ main.cpp" >> Makefile
echo "	@./a.out" >> Makefile

